# How to set up Netlify CMS for Hugo: https://www.netlifycms.org/docs/hugo
# Available options: https://www.netlifycms.org/docs/configuration-options
# Example: https://github.com/netlify/netlify-cms/blob/master/dev-test/config.yml
backend:
  name: git-gateway
  # git Gateway Error: Please ask your site administrator to reissue the Git Gateway token
  # https://community.netlify.com/t/git-gateway-error/12220/8
  branch: main
  commit_messages:
    create: 'Create {{collection}} "{{slug}}"'
    update: 'Update {{collection}} "{{slug}}"'
    delete: 'Delete {{collection}} "{{slug}}"'
    uploadMedia: '[skip ci] Upload "{{path}}"'
    deleteMedia: '[skip ci] Delete "{{path}}"'

# https://www.netlifycms.org/docs/beta-features/#working-with-a-local-git-repository
local_backend: true

media_folder: site/content/img

public_folder: /img

site_url: https://miyamadojinja.com

logo_url: https://user-images.githubusercontent.com/7563926/187314099-ad31bb3e-364d-47c2-a8cc-dce45cf42b7e.svg

locale: 'ja'

show_preview_links: false

search: false

collections:
  - name: 'Fixed pages'
    label: '固定ページ'
    editor:
      preview: false
    files:
      - file: 'site/content/_index.md'
        label: 'ホーム'
        name: 'home'
        fields:
          - label: '写真'
            name: 'mainImage'
            widget: 'image'
            required: false
          - label: 'お知らせ'
            name: 'news'
            widget: 'text'
            required: false
          - label: '序文'
            name: 'introduction'
            widget: 'text'
          - label: '本文'
            name: 'body'
            widget: 'text'
          - label: '御祭神'
            name: 'saijin'
            widget: 'list'
            fields:
              - { label: '名称', name: 'name', widget: 'string' }
              - { label: '説明', name: 'description', widget: 'text', required: false }
              - { label: '写真', name: 'image', widget: 'image', required: false }
              - { label: 'リンクURL', name: 'linkUrl', widget: 'string', required: false }
          - label: '特記事項'
            name: features
            widget: list
            fields:
              - { label: '名称', name: 'name', widget: 'text' }
              - { label: '説明', name: 'description', widget: 'text', required: false }
              - { label: '写真', name: 'image', widget: 'image', required: false }
              - { label: 'リンクURL', name: 'linkUrl', widget: 'string', required: false }
          - label: '厄年表'
            name: 'yakudoshi'
            widget: 'object'
            fields:
              - label: '説明文'
                name: 'caption'
                widget: 'text'
              - label: '男性'
                name: 'men'
                widget: 'list'
                field:
                  label: '年齢区分'
                  name: 'row'
                  widget: 'list'
                  field: { label: '値', name: 'value', widget: 'string' }
              - label: '女性'
                name: 'women'
                widget: 'list'
                field:
                  label: '年齢区分'
                  name: 'row'
                  widget: 'list'
                  field: { label: '値', name: 'value', widget: 'string' }
          - label: '境内写真'
            name: 'keidaiImage'
            widget: 'image'
            required: false
          - label: '境内の見どころ'
            name: 'keidaiSpots'
            widget: list
            fields:
              - { label: '番号', name: 'number', widget: 'number' }
              - { label: '名称', name: 'name', widget: 'string' }
          - label: '交通案内'
            name: 'transportation'
            widget: 'text'
      - file: 'site/content/events.md'
        label: '年間行事'
        name: 'events'
        fields:
          - label: '写真'
            name: 'mainImage'
            widget: 'image'
            required: false
          - label: '本文'
            name: 'body'
            widget: 'text'
      - file: 'site/content/gokito.md'
        label: '御祈祷・出張祭典'
        name: 'gokito'
        fields:
          - label: '写真'
            name: 'mainImage'
            widget: 'image'
            required: false
          - label: '本文'
            name: 'body'
            widget: 'text'
      - file: 'site/content/juyohin.md'
        label: '授与品'
        name: 'juyohin'
        fields:
          - label: '写真'
            name: 'mainImage'
            widget: 'image'
            required: false
          - label: '本文'
            name: 'body'
            widget: 'text'
          - label: 'おふだ説明'
            name: 'ofudaDescription'
            widget: 'string'
            required: false
          - label: 'おふだリスト'
            name: 'ofudaCollection'
            widget: 'list'
            fields:
              - { label: '名称', name: 'name', widget: 'string' }
              - { label: '説明', name: 'description', widget: 'text', required: false }
              - { label: '写真', name: 'image', widget: 'image', required: false }
          - label: 'お守り説明'
            name: 'omamoriDescription'
            widget: 'string'
            required: false
          - label: 'お守りリスト'
            name: 'omamoriCollection'
            widget: 'list'
            fields:
              - { label: '名称', name: 'name', widget: 'string' }
              - { label: '説明', name: 'description', widget: 'text', required: false }
              - { label: '写真', name: 'image', widget: 'image', required: false }
      - file: 'site/content/kyoshiki.md'
        label: '結婚式'
        name: 'kyoshiki'
        fields:
          - label: '写真'
            name: 'mainImage'
            widget: 'image'
            required: false
          - label: '本文'
            name: 'body'
            widget: 'text'
      - file: 'site/content/tenjinzo.md'
        label: '大天神像'
        name: 'tenjinzo'
        fields:
          - label: '写真'
            name: 'mainImage'
            widget: 'image'
            required: false
          - label: '本文'
            name: 'body'
            widget: 'text'
      - file: 'site/content/yomeiri.md'
        label: '狐の嫁入り神事'
        name: 'yomeiri'
        fields:
          - label: '写真'
            name: 'mainImage'
            widget: 'image'
            required: false
          - label: '本文'
            name: 'body'
            widget: 'text'
  - name: blog # Used in routes, ie.: /admin/collections/:slug/edit
    label: 記事 # Used in the UI, ie.: "New Blog Post"
    folder: 'site/content/blog' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{year}}-{{month}}-{{day}}-{{hour}}{{minute}}' # E.g. "2020-01-01-1234"
    editor: { preview: false }
    fields:
      - label: 下書き（未公開）
        name: 'draft'
        widget: 'boolean'
        default: true
        required: false
      - label: 題目
        name: 'title'
        widget: 'string'
      - label: 日付
        name: date
        widget: datetime
        format: 'YYYY-MM-DDTHH:mm:ssZ'
        date_format: true
        time_format: false
        picker_utc: true # so users in all timezones will see the same date in the datetime picker
      - label: '写真'
        name: 'mainImage'
        widget: 'image'
        required: false
      - label: 本文
        name: 'body'
        widget: 'text'
        required: false
      - label: 分類タグ
        name: 'tags'
        widget: 'list'
        required: false
        field: { label: Name, name: name, widget: string }
